version: "3.2"

services:
    testbed:
        build: .
        volumes:
            - ./:/src
            - /mnt/sdf:/data
        entrypoint:
            - /bin/sh
            - -c
            - sleep inf
