version: "3.2"
services:
  backend:
    build: backend
    volumes:
      - .:/src
    networks:
      - cormorant
    ports:
      - 127.0.0.1:7000:7000
  
  mongo:
    image: mongo
    networks:
      - cormorant
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: temp
  
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - cormorant 
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: temp

networks:
  cormorant: